### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by CallioO** [CallioO/nesTic.Cup#3]
![image](https://cloud.githubusercontent.com/assets/17162324/18232255/2b9b1ad4-72cc-11e6-94b6-7da5648883ea.jpeg)
http://zwante.nestic.de/sprachwechsel/uk/return/profil/bearbeiten/email
http://zwante.nestic.de/sprachwechsel/uk/return/profil/bearbeiten/passwort

Ändert man bei "PW/Email ändern" die Sprache kommt der o.g. Fehler.

**Comment by zwantE** [comment]
ist gefixt
